import { SCHEMA_VERSION } from './schemas'
import { PARADIGM_LINE_Y } from './types'
import type {
  BeatKey,
  BeatMarker,
  Project,
  StoryEdge,
  StoryScene,
} from './types'

// Layout constant shared with the canvas background.
export const PHASE_WIDTH = 700

type SceneSeed = Omit<
  StoryScene,
  'order' | 'collapsed' | 'locked' | 'notes'
> &
  Partial<Pick<StoryScene, 'order' | 'collapsed' | 'locked' | 'notes'>>

function scene(index: number, s: SceneSeed): StoryScene {
  return {
    order: index,
    collapsed: false,
    locked: false,
    notes: '',
    ...s,
  }
}

const beats: BeatMarker[] = (
  [
    ['catalyst', 'Catalyst', 'ได้ฟังคำแนะนำจาก Club Friday', 500],
    ['want', 'Want', 'ตั้งใจเขียนสมุดให้ครบ 30 วัน', 720],
    ['progress', 'Things Go Well', 'เริ่มวาดมือชายปริศนาและคิดถึงคิวน้อยลง', 1000],
    ['warning', 'Warning', 'เลสข้อมือของชายปริศนาหายไป', 1220],
    ['midpoint', 'Midpoint', 'ชายปริศนาหายไปหลายวัน', 1400],
    ['ghost', 'Ghost', 'ความทรงจำเกี่ยวกับรุ่นพี่มหาวิทยาลัยกลับมา', 1650],
    ['low_point', 'Low Point', 'ภาพรุ่นพี่ ชายปริศนา และคิวซ้อนทับกัน', 1900],
    ['aha', 'Aha!', 'แอลเข้าใจว่าความเงียบสร้างบาดแผลทั้งสองฝ่าย', 2100],
    ['choice', 'Choice', 'แอลโทรหาคิวในวันที่ 26', 2320],
    ['climax', 'Climax', 'แอลเป็นฝ่ายเอ่ยปากทักชายปริศนาก่อน', 2560],
    ['ending', 'Ending', 'กล้าเชื่อมต่อกับคนอื่นอีกครั้ง', 2760],
  ] as [BeatKey, string, string, number][]
).map(([type, title, description, x]) => ({
  id: `beat-${type}`,
  type,
  title,
  description,
  position: { x, y: PARADIGM_LINE_Y - 12 },
  locked: false,
}))

const scenes: StoryScene[] = [
  scene(0, {
    id: 'scene-ghost-bg',
    title: 'รุ่นพี่ตัดขาดแอล',
    location: 'มหาวิทยาลัย (อดีต)',
    characters: ['แอล', 'รุ่นพี่'],
    povCharacter: 'แอล',
    characterGoal: 'อยากเข้าใจว่าทำไมถูกตัดขาด',
    action: 'พยายามติดต่อรุ่นพี่ทุกช่องทาง',
    obstacle: 'รุ่นพี่เงียบและบล็อกทุกช่องทางโดยไม่อธิบาย',
    outcome: 'แอลวาดภาพไม่ได้และดร็อปเรียน',
    changeAfterScene: 'แอลเชื่อว่าการเงียบก่อนคือการป้องกันตัว',
    phase: 'setup',
    beat: undefined,
    arcRelation: 'ghost',
    position: { x: 60, y: 160 },
  }),
  scene(1, {
    id: 'scene-catalyst',
    title: 'คำแนะนำจาก Club Friday',
    location: 'ห้องพักของแอล',
    characters: ['แอล'],
    povCharacter: 'แอล',
    characterGoal: 'หาวิธีก้าวข้ามการเลิกกับคิว',
    action: 'ฟังรายการและจดคำแนะนำเรื่องการเขียนระบาย',
    obstacle: 'ยังคิดถึงคิวจนนอนไม่หลับ',
    outcome: 'ตัดสินใจจะลองเขียนสมุด',
    changeAfterScene: 'มีเป้าหมายใหม่ที่จับต้องได้',
    phase: 'setup',
    beat: 'catalyst',
    arcRelation: 'neutral',
    position: { x: 360, y: 150 },
  }),
  scene(2, {
    id: 'scene-want',
    title: 'เริ่มเขียนสมุด 30 วัน',
    location: 'ห้องสต็อก',
    characters: ['แอล'],
    povCharacter: 'แอล',
    characterGoal: 'ต้องการลืมคิว',
    action: 'เขียนถึงคิวเต็มหน้าทุกคืน',
    obstacle: 'ยังอยากทักคิว',
    outcome: 'ผ่านสิบวันแรกได้',
    changeAfterScene: 'แอลเชื่อว่าวิธีนี้อาจได้ผล',
    phase: 'early',
    beat: 'want',
    arcRelation: 'want',
    position: { x: 740, y: -300 },
  }),
  scene(3, {
    id: 'scene-progress',
    title: 'วาดมือชายปริศนา',
    location: 'ร้านสะดวกซื้อ',
    characters: ['แอล', 'ชายปริศนา'],
    povCharacter: 'แอล',
    characterGoal: 'อยากรู้จักลูกค้าประจำคนนี้',
    action: 'สังเกตตะกร้าลูกค้าและวาดมือชายปริศนา',
    obstacle: 'ไม่กล้าเอ่ยปากทัก',
    outcome: 'คิดถึงคิวน้อยลง',
    changeAfterScene: 'เริ่มเปิดใจให้คนใหม่โดยไม่รู้ตัว',
    phase: 'early',
    beat: 'progress',
    arcRelation: 'want',
    position: { x: 1000, y: -300 },
  }),
  scene(4, {
    id: 'scene-warning',
    title: 'เลสข้อมือหายไป',
    location: 'ร้านสะดวกซื้อ',
    characters: ['แอล', 'เพื่อน'],
    povCharacter: 'แอล',
    characterGoal: 'อยากให้ทุกอย่างเป็นไปตามที่คุม',
    action: 'มองหาชายปริศนาและสังเกตว่าเลสข้อมือหายไป',
    obstacle: 'เพื่อนแซวจนแอลเขิน',
    outcome: 'รู้สึกไม่มั่นคงกับความสัมพันธ์ที่เพิ่งเริ่ม',
    changeAfterScene: 'ความกลัวการถูกทิ้งเริ่มกลับมา',
    phase: 'early',
    beat: 'warning',
    arcRelation: 'neutral',
    position: { x: 1180, y: -520 },
  }),
  scene(5, {
    id: 'scene-midpoint',
    title: 'ชายปริศนาหายไป',
    location: 'ร้านสะดวกซื้อ',
    characters: ['แอล'],
    povCharacter: 'แอล',
    characterGoal: 'อยากให้ชายปริศนากลับมา',
    action: 'รอและเฝ้ามองประตูร้านทุกกะ',
    obstacle: 'ชายปริศนาหายไปหลายวันโดยไม่มีคำอธิบาย',
    outcome: 'แอลเริ่มตื่นตระหนก',
    changeAfterScene: 'ความเงียบของอีกฝ่ายกระตุ้นบาดแผลเดิม',
    phase: 'middle',
    beat: 'midpoint',
    arcRelation: 'lie',
    position: { x: 1420, y: 150 },
  }),
  scene(6, {
    id: 'scene-ghost',
    title: 'อดีตย้อนกลับมา',
    location: 'ห้องพักของแอล',
    characters: ['แอล'],
    povCharacter: 'แอล',
    characterGoal: 'อยากหนีความรู้สึกถูกทิ้ง',
    action: 'นึกถึงรุ่นพี่และความเงียบในอดีต',
    obstacle: 'ภาพความทรงจำท่วมท้น',
    outcome: 'แอลเริ่มคิดจะตัดขาดชายปริศนาก่อน',
    changeAfterScene: 'Lie ทำงานเต็มที่ — เงียบก่อนเพื่อไม่ให้เจ็บ',
    phase: 'middle',
    beat: 'ghost',
    arcRelation: 'ghost',
    position: { x: 1620, y: 370 },
  }),
  scene(7, {
    id: 'scene-lowpoint',
    title: 'ภาพซ้อนทับกัน',
    location: 'ห้องพักของแอล',
    characters: ['แอล'],
    povCharacter: 'แอล',
    characterGoal: 'อยากให้ความเจ็บหยุดลง',
    action: 'จมอยู่กับภาพรุ่นพี่ ชายปริศนา และคิวที่ซ้อนทับกัน',
    obstacle: 'แยกไม่ออกว่ากลัวอะไรกันแน่',
    outcome: 'แอลดิ่งถึงจุดต่ำสุด',
    changeAfterScene: 'พร้อมจะยอมรับความจริงบางอย่าง',
    phase: 'middle',
    beat: 'low_point',
    arcRelation: 'ghost',
    position: { x: 1880, y: 150 },
  }),
  scene(8, {
    id: 'scene-aha',
    title: 'เข้าใจความเงียบ',
    location: 'ห้องพักของแอล',
    characters: ['แอล'],
    povCharacter: 'แอล',
    characterGoal: 'อยากเข้าใจตัวเอง',
    action: 'ทบทวนว่าการเงียบของตนทำร้ายใคร',
    obstacle: 'ต้องยอมรับว่าตัวเองก็เคยทำให้คนอื่นเจ็บ',
    outcome: 'เข้าใจว่าความเงียบเป็นการย้ายบาดแผลให้อีกคน',
    changeAfterScene: 'Need เริ่มปรากฏ — กล้าเชื่อมต่อกับคนอื่น',
    phase: 'ending',
    beat: 'aha',
    arcRelation: 'need',
    position: { x: 2100, y: 150 },
  }),
  scene(9, {
    id: 'scene-choice',
    title: 'โทรหาคิว',
    location: 'ห้องพักของแอล',
    characters: ['แอล', 'คิว'],
    povCharacter: 'แอล',
    characterGoal: 'อยากปิดเรื่องเก่าอย่างตรงไปตรงมา',
    action: 'โทรหาคิวในวันที่ 26 เพื่อพูดในสิ่งที่ไม่เคยพูด',
    obstacle: 'กลัวว่าจะถูกเงียบใส่อีก',
    outcome: 'ได้พูดความในใจและปล่อยวางได้',
    changeAfterScene: 'เลิกใช้ความเงียบเป็นเกราะ',
    phase: 'ending',
    beat: 'choice',
    arcRelation: 'need',
    position: { x: 2320, y: 370 },
  }),
  scene(10, {
    id: 'scene-climax',
    title: 'ทักชายปริศนาก่อน',
    location: 'ร้านสะดวกซื้อ',
    characters: ['แอล', 'ชายปริศนา'],
    povCharacter: 'แอล',
    characterGoal: 'อยากเริ่มต้นความสัมพันธ์อย่างกล้าหาญ',
    action: 'เอ่ยปากทักชายปริศนาก่อนเป็นครั้งแรก',
    obstacle: 'ต้องเอาชนะความกลัวการถูกปฏิเสธ',
    outcome: 'ไม่ได้เขียนครบ 30 วัน แต่กล้าเชื่อมต่อกับคนอื่นอีกครั้ง',
    changeAfterScene: 'แอลได้สิ่งที่ดีกว่า Want เดิม',
    phase: 'ending',
    beat: 'climax',
    arcRelation: 'need',
    position: { x: 2540, y: -300 },
  }),
]

const edges: StoryEdge[] = [
  edge('e-actual-1', 'scene-ghost-bg', 'scene-catalyst', 'actual_path'),
  edge('e-actual-2', 'scene-catalyst', 'scene-want', 'actual_path'),
  edge('e-actual-3', 'scene-want', 'scene-progress', 'actual_path'),
  edge('e-actual-4', 'scene-progress', 'scene-warning', 'actual_path'),
  edge('e-actual-5', 'scene-warning', 'scene-midpoint', 'actual_path'),
  edge('e-actual-6', 'scene-midpoint', 'scene-ghost', 'actual_path'),
  edge('e-actual-7', 'scene-ghost', 'scene-lowpoint', 'actual_path'),
  edge('e-actual-8', 'scene-lowpoint', 'scene-aha', 'actual_path'),
  edge('e-actual-9', 'scene-aha', 'scene-choice', 'actual_path'),
  edge('e-actual-10', 'scene-choice', 'scene-climax', 'actual_path'),
  edge('e-expected', 'scene-want', 'scene-climax', 'expected_want_path'),
  edge('e-failure', 'scene-midpoint', 'scene-lowpoint', 'failure_path'),
  edge('e-better', 'scene-aha', 'scene-climax', 'better_outcome_path'),
  edge('e-arc', 'scene-ghost-bg', 'scene-aha', 'character_arc'),
]

function edge(
  id: string,
  source: string,
  target: string,
  type: StoryEdge['type'],
): StoryEdge {
  return { id, source, target, type }
}

// A demonstrative non-linear telling: start at the crisis (A), flash back to
// the origin (B), then move forward — telling order ≠ chronological order.
const TELLING_MAP: Record<string, string> = {
  'scene-midpoint': 'A',
  'scene-ghost-bg': 'B',
  'scene-catalyst': 'B',
  'scene-want': 'C',
  'scene-progress': 'C',
  'scene-warning': 'C',
  'scene-ghost': 'D',
  'scene-lowpoint': 'D',
  'scene-aha': 'D',
  'scene-choice': 'E',
  'scene-climax': 'E',
}

export function createSeedProject(): Project {
  return {
    schemaVersion: SCHEMA_VERSION,
    id: 'seed-al',
    title: 'แอล — ตะกร้าคนใจสลาย',
    backstory: {
      ghost:
        'แอลเคยถูกคนรักรุ่นพี่ตัดขาดทุกช่องทางโดยไม่อธิบาย จนวาดภาพไม่ได้และดร็อปเรียน',
      lie: 'ผมจะไม่เจ็บอีก ถ้าผมเป็นคนกำหนดว่าเรื่องจะจบตอนไหน และไม่ปล่อยให้ใครมาเงียบใส่ผมก่อน',
      lieAtWork: 'แอลเป็นฝ่ายเงียบและตัดความสัมพันธ์ก่อนเสมอ',
      want: 'เขียนระบายความคิดถึงให้ครบ 30 วันติดต่อกันเพื่อลืมคิว',
      need: 'ความเงียบไม่ได้ปกป้องใคร แต่เป็นการย้ายบาดแผลไปให้อีกคนหนึ่ง',
    },
    scenes: scenes.map((s) => ({ ...s, tellingChapter: TELLING_MAP[s.id] })),
    beats,
    edges,
    climaxOutcome: { want: 'not_got', need: 'gained' },
    structureTemplateId: 'four-phase',
    tellingChapterOrder: ['A', 'B', 'C', 'D', 'E'],
    characters: [
      {
        id: 'ch-al',
        name: 'แอล',
        color: '#e49c4e',
        ghost: 'ถูกคนรักรุ่นพี่ตัดขาดโดยไม่อธิบาย',
        lie: 'ถ้าผมเงียบและตัดก่อน ผมจะไม่เจ็บ',
        lieAtWork: 'เป็นฝ่ายเงียบก่อนเสมอ',
        want: 'เขียนสมุดครบ 30 วันเพื่อลืมคิว',
        need: 'ความเงียบย้ายบาดแผล ไม่ได้ปกป้องใคร',
      },
      {
        id: 'ch-q',
        name: 'คิว',
        color: '#cd5042',
        ghost: '',
        lie: '',
        lieAtWork: '',
        want: '',
        need: '',
      },
      {
        id: 'ch-stranger',
        name: 'ชายปริศนา',
        color: '#3d4dec',
        ghost: '',
        lie: '',
        lieAtWork: '',
        want: '',
        need: '',
      },
      {
        id: 'ch-senior',
        name: 'รุ่นพี่',
        color: '#8a6fb3',
        ghost: '',
        lie: '',
        lieAtWork: '',
        want: '',
        need: '',
      },
      {
        id: 'ch-friend',
        name: 'เพื่อน',
        color: '#2f9c6c',
        ghost: '',
        lie: '',
        lieAtWork: '',
        want: '',
        need: '',
      },
    ],
    synopsis:
      'แอลพยายามลืมคนรักเก่าด้วยการเขียนสมุด 30 วัน แต่กลับได้เรียนรู้ว่าความเงียบที่เขาใช้ปกป้องตัวเองคือสิ่งที่ทำร้ายคนอื่น — และกล้าเอ่ยปากทักคนใหม่ก่อนเป็นครั้งแรก',
    tellingChapterNotes: {
      A: 'เปิดเรื่องกลางวิกฤต: ชายปริศนาหายไป แอลตื่นตระหนก',
      B: 'ย้อนปูมหลัง: รุ่นพี่ตัดขาด และคำแนะนำจาก Club Friday',
      C: 'ช่วงชีวิตดูดีขึ้น: เขียนสมุด วาดมือชายปริศนา',
      D: 'ดิ่งลง: อดีตย้อนกลับ ภาพซ้อนทับ จน Aha',
      E: 'ตัดสินใจและไคลแมกซ์: โทรหาคิว แล้วทักชายปริศนาก่อน',
    },
    viewport: { x: 40, y: 360, zoom: 0.8 },
    updatedAt: new Date('2026-07-23T00:00:00.000Z').toISOString(),
  }
}
